/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, animated } from '@react-spring/three'
import * as THREE from 'three'

interface NextjsModelProps {
    scale?: any
    onClick?: () => void
    onPointerOver?: () => void
    onPointerOut?: () => void
}

export function NextjsModel(props: NextjsModelProps) {
    const { nodes, materials } = useGLTF('/nextjs.gltf') as any
    return (
        <animated.group {...props} dispose={null}>
            <group rotation={[0, Math.PI / 4, 0]} scale={[0.254, -0.254, 0.254]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.mesh_0 as THREE.Mesh).geometry}
                    material={(nodes.mesh_0 as THREE.Mesh).material}
                    position={[-197, -39.716, -2.5]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.mesh_1 as THREE.Mesh).geometry}
                    material={(nodes.mesh_1 as THREE.Mesh).material}
                    position={[-197, -39.716, -2.5]}
                    scale={[1.01, 1.01, 1.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.mesh_2 as THREE.Mesh).geometry}
                    material={(nodes.mesh_2 as THREE.Mesh).material}
                    position={[-197, -39.716, -2.5]}
                    scale={[1.01, 1.01, 1.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.mesh_3 as THREE.Mesh).geometry}
                    material={(nodes.mesh_3 as THREE.Mesh).material}
                    position={[-197, -39.716, -2.5]}
                    scale={[1.01, 1.01, 1.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.mesh_4 as THREE.Mesh).geometry}
                    material={(nodes.mesh_4 as THREE.Mesh).material}
                    position={[-197, -39.716, -2.5]}
                    scale={[1.01, 1.01, 1.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.mesh_5 as THREE.Mesh).geometry}
                    material={(nodes.mesh_5 as THREE.Mesh).material}
                    position={[-197, -39.716, -2.5]}
                    scale={[1.01, 1.01, 1.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.mesh_6 as THREE.Mesh).geometry}
                    material={(nodes.mesh_6 as THREE.Mesh).material}
                    position={[-197, -39.716, -2.5]}
                    scale={[1.01, 1.01, 1.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.mesh_7 as THREE.Mesh).geometry}
                    material={(nodes.mesh_7 as THREE.Mesh).material}
                    position={[-197, -39.716, -2.5]}
                    scale={[1.01, 1.01, 1.06]}
                />
            </group>
        </animated.group>
    )
}

useGLTF.preload('/nextjs.gltf')
