/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, animated } from '@react-spring/three'
import * as THREE from 'three'

interface TailwindModelProps {
    scale?: any
    onClick?: () => void
    onPointerOver?: () => void
    onPointerOut?: () => void
}

export function TailwindModel(props: TailwindModelProps) {
    const { nodes, materials } = useGLTF('/tailwindcss.gltf') as any
    return (
        <animated.group {...props} dispose={null}>
            <group position={[-0.009, 0, 0.009]}>
                <group rotation={[0, Math.PI / 4, 0]} scale={[0.382, -0.382, 0.382]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_0 as THREE.Mesh).geometry}
                        material={(nodes.mesh_0 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_1 as THREE.Mesh).geometry}
                        material={(nodes.mesh_1 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_2 as THREE.Mesh).geometry}
                        material={(nodes.mesh_2 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_3 as THREE.Mesh).geometry}
                        material={(nodes.mesh_3 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_4 as THREE.Mesh).geometry}
                        material={(nodes.mesh_4 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_5 as THREE.Mesh).geometry}
                        material={(nodes.mesh_5 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_6 as THREE.Mesh).geometry}
                        material={(nodes.mesh_6 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_7 as THREE.Mesh).geometry}
                        material={(nodes.mesh_7 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_8 as THREE.Mesh).geometry}
                        material={(nodes.mesh_8 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_9 as THREE.Mesh).geometry}
                        material={(nodes.mesh_9 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_10 as THREE.Mesh).geometry}
                        material={(nodes.mesh_10 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_11 as THREE.Mesh).geometry}
                        material={(nodes.mesh_11 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_12 as THREE.Mesh).geometry}
                        material={(nodes.mesh_12 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_13 as THREE.Mesh).geometry}
                        material={(nodes.mesh_13 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.mesh_14 as THREE.Mesh).geometry}
                        material={(nodes.mesh_14 as THREE.Mesh).material}
                        position={[-130.666, -16.2, -2.5]}
                        scale={[1.01, 1.01, 1.06]}
                    />
                </group>
            </group>
        </animated.group>
    )
}

useGLTF.preload('/tailwindcss.gltf')
